export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const UPDATE_IN_SUCCESS = 'UPDATE_IN_SUCCESS';
export const UPDATE_IN_ERROR = 'UPDATE_IN_ERROR';
export const LIST_SUCCESS ='LIST_SUCCESS';
export const EDIT_IN_SUCCESS ='EDIT_IN_SUCCESS';
export const DELETE_IN_SUCCESS = 'DELETE_IN_SUCCESS';
export const ADD_IN_SUCCESS = 'ADD_IN_SUCCESS';


